### ISSUE TITLE
error while writing out vendor tree

### ISSUE THREAD

**Issue by timcappalli** [smallstep/homebrew-smallstep#2]
See this on upgrade from 0.8.1 to 0.10.0 (macOS 10.14.6)

`
==> Installing smallstep/smallstep/step
==> Downloading https://github.com/smallstep/cli/releases/download/v0.10.0/step-cli_0.10.0.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/141352703/1ff6f980-6b3c-11e9-8167-1edad0639806?X-Amz-Algorithm=AW
######################################################################## 100.0%
==> make build
Last 15 lines from /Users/timc/Library/Logs/Homebrew/step/01.make:
2019-08-20 08:44:28 -0400

make
build

grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/golang/lint: fatal: failed to unpack tree object 883fe33ffc4344bad1ecd881f61afd5ec5d80e0a
: exit status 128
make: *** [vendor] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/smallstep/homebrew-smallstep/issues
`

**Comment by dopey** [comment]
hey @timcappalli, I'm wondering if you'll see this same error if you build from the homebrew core. Would you mind trying:

```
$ brew untap smallstep/smallstep
$ brew uninstall step
$ brew install step
```

That error is generally an indication that another process was using `dep` at the same time. Assuming that's not the case, maybe the vendor directory got corrupted. Regardless, I would try uninstalling and then reinstalling `step` to see if that fixes it. Let me know if that doesn't help and I can continue to help with debugging.

**Comment by timcappalli** [comment]
That seems to have worked!

**Comment by dopey** [comment]
I did some more sleuthing on this bug today because all of our golang projects were no longer building in CI. The problem was that one of the packages we use for linting (golint) deleted the branch and revision that we had pinned in our `Gopkg.toml`. Anything that was building the code from scratch would have gotten snagged on this error. When you use our local homebrew tap it downloads the code and tries to build on your laptop. Whereas the tap served by homebrew-core caches versions of the binaries (bottles in brew speak) that get prebuilt at the time when the tap is created. That's why installing from homebrew core does not cause an error, while the local tap does.

We try and make sure the core tap matches our local tap, with respect to the release #, so there shouldn't be any real reason to use the local tap at this time. Maybe in the future we'll have nightly builds and then we'd host those on the local tap. For now though, and for 99% of use cases, the core tap is the way to go. 

Thanks for bringing this issue to our attention! Made it easier to track down the problem.

cheers :)
